### ISSUE TITLE
Please release a windows client

### ISSUE THREAD

**Issue by wutongskype** [samhocevar/rinetd#17]
Please release a windows client，thk

**Comment by samhocevar** [comment]
Hi, and sorry for taking so long. You can now build rinetd with Visual Studio (in the `main` branch), and the next release will have a Windows version.

**Comment by samhocevar** [comment]
There is a Windows executable with the [rinetd 0.71](https://github.com/samhocevar/rinetd/releases/tag/v0.71) release, so I’m marking this as fixed.
