### ISSUE TITLE
Build under Centos 6.7 i386 Centos 7 x64

### ISSUE THREAD

**Issue by WuvorWenda** [samhocevar/rinetd#2]
Hello,
Build under Ubuntu is fine. But i get a error building under Centos 32 and 64. glibc 2.12
Centos 6.7 and Centos 7 x64
What to do?
# make
make  all-am
make[1]: Entering directory `/usr/src/rinetd-master'
gcc -DHAVE_CONFIG_H -I.    -std=c99 -D_XOPEN_SOURCE -D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=200809L -Wall -Wextra -Wwrite-strings -I. -g -O2 -MT rinetd-rinetd.o -MD -MP -MF .deps/rinetd-rinetd.Tpo -c -o rinetd-rinetd.o `test -f 'rinetd.c' || echo './'`rinetd.c
rinetd.c: In function ‘getAddress’:
rinetd.c:1152: error: ‘h_errno’ undeclared (first use in this function)
rinetd.c:1152: error: (Each undeclared identifier is reported only once
rinetd.c:1152: error: for each function it appears in.)
rinetd.c:1154: error: ‘HOST_NOT_FOUND’ undeclared (first use in this function)
rinetd.c:1157: error: ‘NO_ADDRESS’ undeclared (first use in this function)
rinetd.c:1160: error: ‘NO_RECOVERY’ undeclared (first use in this function)
rinetd.c:1163: error: ‘TRY_AGAIN’ undeclared (first use in this function)
rinetd.c:1172: error: ‘struct hostent’ has no member named ‘h_addr’
make[1]: *** [rinetd-rinetd.o] Error 1

Thank you,

**Comment by insom** [comment]
Hi @WuvorWenda -- I found that changing the `_DEFAULT_SOURCE` define out for a `_GNU_SOURCE` one enabled me to compile this on Ubuntu 12.04.4. I hope that helps!

**Comment by WuvorWenda** [comment]
Hi @insom Thank you.
It compile just right now, no errors.
Great trick.
Thanks again.
