### ISSUE TITLE
Configuration parse error with some hostnames

### ISSUE THREAD

**Issue by samhocevar** [samhocevar/rinetd#20]
This happens when a hostname starts with `[0-9a-f]*` because it is incorrectly parsed as an IPv6.

Fixed in e3b47d086a368becf36820b7927a2453c93c5c96.

**Comment by pjao** [comment]
Hi @samhocevar 

Fix one, broke another. This special case "::1".

rinetd: invalid syntax at line 24: ::1     5103 192.168.1.111 80

**Comment by samhocevar** [comment]
Thanks again! I really messed up with the PEG grammar when I added IPv6 support and overlooked many things, but it should behave correctly now.

**Comment by pjao** [comment]
Thanks for all your work. 

Yes, it looks like now, everything is back to work very nice. Go head with release fix.

**Comment by samhocevar** [comment]
Version 0.73 is now out and hopefully fixes all this mess! Thanks for the testing.
