### ISSUE TITLE
rinetd 0.71 build issue

### ISSUE THREAD

**Issue by chenrui333** [samhocevar/rinetd#21]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>build failure</summary>

```
rinetd.c:799:19: error: use of undeclared identifier 'NI_MAXHOST'
        char addressText[NI_MAXHOST];
                         ^
rinetd.c:924:19: error: use of undeclared identifier 'NI_MAXHOST'
        char addressText[NI_MAXHOST] = { '?' };
                         ^
2 errors generated.
make[2]: *** [___rinetd-rinetd.o] Error 1
make[2]: *** Waiting for unfinished jobs....
mv -f .deps/___rinetd-match.Tpo .deps/___rinetd-match.Po
mv -f .deps/___rinetd-parse.Tpo .deps/___rinetd-parse.Po
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1
```

</details>

Full build log is in here, https://github.com/Homebrew/homebrew-core/runs/1907745906
relates to https://github.com/Homebrew/homebrew-core/pull/71237

**Comment by samhocevar** [comment]
This was already fixed in version 0.72. But note that 0.73 is now out and fixes an issue with configuration parsing, so I recommend directly using that version.
