### ISSUE TITLE
Does it support ipv6?

### ISSUE THREAD

**Issue by notaganin** [samhocevar/rinetd#25]
I saw the 0.71 version mentioned to support IPv6, but I can't connect my vps with IPv6, the vps has IPv6 & IPv4, maybe it does not support IPv6 & IPv4 machine? Or is my configuration wrong? 
These are the configurations I have used:
1. `0.0.0.0 12345/tcp domain.name.com 23456/tcp`
`0.0.0.0 12345/udp domain.name.com 23456/udp`
2. `0.0.0.0 12345/tcp domain.name.com 23456/tcp`
`0.0.0.0 12345/udp domain.name.com 23456/udp`
`::1 12345/tcp domain.name.com 23456/tcp`
`::1 12345/udp domain.name.com 23456/udp`
3. `::1 12345/tcp domain.name.com 23456/tcp`
`::1 12345/udp domain.name.com 23456/udp`

**Comment by notaganin** [comment]
Maybe there is a problem with the dns resolution policy of this resolver? I see a similar tool called realm, the dns resolution policy is `If a domain is passed, the resolver will try to resolve and update the ip address regularly, ipv4 is preferred.` It causes that if you connect with ipv6, you will not be able to connect to the forwarded domain because the domain resolves to ipv4. Maybe it's the same situation?

**Comment by Ansen** [comment]
@notaganin
ipv6 config example:

`:: 12345/udp domain.name.com 23456/udp`

**Comment by notaganin** [comment]
> @notaganin ipv6 config example:
> 
> `:: 12345/udp domain.name.com 23456/udp`

It works, thank you.
