### ISSUE TITLE
crash on MingW/x64

### ISSUE THREAD

**Issue by ppanhoto78** [samhocevar/rinetd#5]
When I built the software using MinGW (x64), I've got a crash in the function selectPass. After watching the behaviour of select() on windows, I've got this patch to make it work:

```
@@ -572,9 +573,15 @@ static ConnectionInfo *findAvailableConnection(void)
 static void selectPass(void) {

    int const fdSetCount = maxfd / FD_SETSIZE + 1;
+#ifndef _WIN32
 #      define FD_ZERO_EXT(ar) for (int i = 0; i < fdSetCount; ++i) { FD_ZERO(&(ar)[i]); }
 #      define FD_SET_EXT(fd, ar) FD_SET((fd) % FD_SETSIZE, &(ar)[(fd) / FD_SETSIZE])
 #      define FD_ISSET_EXT(fd, ar) FD_ISSET((fd) % FD_SETSIZE, &(ar)[(fd) / FD_SETSIZE])
+#else
+#      define FD_ZERO_EXT(ar) FD_ZERO(ar);
+#      define FD_SET_EXT(fd, ar) FD_SET(fd, ar)
+#      define FD_ISSET_EXT(fd, ar) FD_ISSET(fd, ar)
+#endif

    fd_set readfds[fdSetCount], writefds[fdSetCount];
    FD_ZERO_EXT(readfds);
```

**Comment by samhocevar** [comment]
Thanks for reporting the issue. However the patch does not look correct to me, as it will fail to initialise fd sets beyond the first, so any connection after the first `FD_SETSIZE` will be unusable. I will have a closer look at it.

**Comment by ppanhoto78** [comment]
select() on windows won't make use of the fd_set array beyond the first element and that's been correctly handled in the code, as it does not increase maxfd on WIN32. If you want more than 64 sockets, you need to redefine FD_SETSIZE before including winsock2.h

source: https://msdn.microsoft.com/en-us/library/windows/desktop/ms739169(v=vs.85).aspx

diff --git a/rinetd.c b/rinetd.c
index a54097e..9c5aa4e 100644
--- a/rinetd.c
+++ b/rinetd.c
@@ -7,8 +7,9 @@
 #endif
 
 #if _WIN32
+#	define FD_SETSIZE 1024
+#	include <winsock2.h>
 #	include <windows.h>
-#	include <winsock.h>
 #	include "getopt.h"
 #	define syslog fprintf
 #	define LOG_ERR stderr
@@ -572,9 +573,15 @@ static ConnectionInfo *findAvailableConnection(void)
 static void selectPass(void) {

    int const fdSetCount = maxfd / FD_SETSIZE + 1;
+#ifndef _WIN32
 #      define FD_ZERO_EXT(ar) for (int i = 0; i < fdSetCount; ++i) { FD_ZERO(&(ar)[i]); }
 #      define FD_SET_EXT(fd, ar) FD_SET((fd) % FD_SETSIZE, &(ar)[(fd) / FD_SETSIZE])
 #      define FD_ISSET_EXT(fd, ar) FD_ISSET((fd) % FD_SETSIZE, &(ar)[(fd) / FD_SETSIZE])
+#else
+#      define FD_ZERO_EXT(ar) FD_ZERO(ar);
+#      define FD_SET_EXT(fd, ar) FD_SET(fd, ar)
+#      define FD_ISSET_EXT(fd, ar) FD_ISSET(fd, ar)
+#endif
 
-#	define FD_ZERO_EXT(ar) for (int i = 0; i < fdSetCount; ++i) { FD_ZERO(&(ar)[i]); }
-#	define FD_SET_EXT(fd, ar) FD_SET((fd) % FD_SETSIZE, &(ar)[(fd) / FD_SETSIZE])
-#	define FD_ISSET_EXT(fd, ar) FD_ISSET((fd) % FD_SETSIZE, &(ar)[(fd) / FD_SETSIZE])
 
 	fd_set readfds[fdSetCount], writefds[fdSetCount];
 	FD_ZERO_EXT(readfds);
