### ISSUE TITLE
Add IPv6 support

### ISSUE THREAD

**Issue by samhocevar** [samhocevar/rinetd#7]
This shouldn’t be really hard to implement, and it’s important, because IPv6 will clearly be the protocol of the year 2000.

**Comment by zem** [comment]
+1

**Comment by neggs** [comment]
+1

**Comment by pjao** [comment]
+1

Any news or idea about this?

**Comment by fivetime** [comment]
Add IPv6 support + 1

**Comment by Moebyte** [comment]
+1

**Comment by moonpyk** [comment]
+1

**Comment by sir-reynolds** [comment]
+100

**Comment by samhocevar** [comment]
I added IPv6 support in [rinetd 0.71](https://github.com/samhocevar/rinetd/releases/tag/v0.71). Happy Valentine’s Day everyone.

**Comment by pjao** [comment]
Something went really bad.

With the conf "0.0.0.0 5103 192.168.1.111 80"
we get 
"couldn't bind to address 0.0.0.0 port 80 (Address already in use)"

It looks like is trying to bind destination port and not source port.

**Comment by samhocevar** [comment]
@pjao Sorry about that, I managed to break the configuration parser. I made [a bugfix release](https://github.com/samhocevar/rinetd/releases/tag/v0.72).

**Comment by pjao** [comment]
Thanks @samhocevar !

But it looks like another problem with parser, when the hostname starts with only a number.

rinetd: invalid syntax at line 32: 0.0.0.0 2553 329.getmyip.com 3553

**Comment by samhocevar** [comment]
@pjao sorry about that, it’s due from insufficient testing on my side. I have reported it in #20 and hopefully fixed it in e3b47d086a368becf36820b7927a2453c93c5c96. Please use that issue to report additional problems that may arise.
